include:
  - project: 'infra/gitlab-ci-templates'
    file:
      - workflow.yml
      - test-npm.yml
      - validate-version.yml
      - create-tag.yml
      - create-snapshot-tag.yml
      - release-npm.yml

stages:
  - validate
  - tag
  - release

variables:
  VERSION_CMD: "grep '\"version\"' package.json | head -1 | sed 's/.*\"\\([0-9.]*\\)\".*/\\1/'"

test:
  script:
    - npm run lint
    - npm run lint:eo
    - npm test
